{% set name = "e3sm-tools" %}
{% set version = "3.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/E3SM-Project/E3SM/archive/v{{ version }}.tar.gz
    sha256: f307789973d5696175bccb3f1b35d9a326a94d45340aeeb1260938ad1d0a715c
    patches:
      - 0001-fix-boz-erros-in-mksurfdata_map-build.patch

build:
  skip: true  # [not linux]
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - python
    - libcurl
    - netcdf-fortran
    - netcdf-fortran * nompi_*
  run:
    - python
    - numba
    - numpy
    - xarray

test:
  commands:
    - test -f "${PREFIX}/bin/cube_to_target"
    - test -f "${PREFIX}/bin/interpinic"
    - test -f "${PREFIX}/bin/mksurfdata_map"
    - generate_domain_files_E3SM.py --help
    - mkatmsrffile.py --help

about:
  home: https://e3sm.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools needed to integrate new meshes into the Energy Exascale Earth System Model (E3SM)
  doc_url: https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/872579110/Running+E3SM+on+New+Atmosphere+Grids
  dev_url: https://github.com/E3SM-Project/E3SM

extra:
  recipe-maintainers:
    - altheaden
    - xylar
