{% set name = "e3sm-tools" %}
{% set version = "3.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/E3SM-Project/E3SM/archive/v{{ version }}.tar.gz
    sha256: 91a515314da042932bf0610a0607c610e5bfeac43700dc64a4b49cb92b37184e
    patches:
      - 0001-fix-boz-erros-in-mksurfdata_map-build.patch

build:
  skip: true  # [not linux]
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('fortran') }}
    - {{ stdlib("c") }}
    - cmake
    - make
  host:
    - libcurl
    - netcdf-fortran
    - netcdf-fortran * nompi_*

test:
  commands:
    - test -f "${PREFIX}/bin/cube_to_target"
    - test -f "${PREFIX}/bin/interpinic"
    - test -f "${PREFIX}/bin/mksurfdata_map"

about:
  home: https://e3sm.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Tools needed to integrate new meshes into the Energy Exascale Earth System Model (E3SM)
  doc_url: https://acme-climate.atlassian.net/wiki/spaces/DOC/pages/872579110/Running+E3SM+on+New+Atmosphere+Grids
  dev_url: https://github.com/E3SM-Project/E3SM

extra:
  recipe-maintainers:
    - altheaden
    - xylar
